$if[$or[$var[p]==userinfo;$var[p]==ui;$var[p]==infouser;$var[p]==iu]==true]
https://raw.githubusercontent.com/Demom23345/Belzebu/main/Comandos/Utilidade/Userinfo.ruby
$elseif[$or[$var[p]==avatar;$var[p]==usericon;$var[p]==iconuser]==true]
https://raw.githubusercontent.com/Demom23345/Belzebu/main/Comandos/Utilidade/Avatar.ruby
$elseif[$or[$var[p]==servericon;$var[p]==iconserver]==true]
https://raw.githubusercontent.com/Demom23345/Belzebu/main/Comandos/Utilidade/Servericon.ruby
$elseif[$var[p]==servers]
https://raw.githubusercontent.com/Demom23345/Belzebu/main/Comandos/Developers/Server.ruby
$endif
